### ISSUE TITLE
Cannot read property 'max' of undefined.

### ISSUE THREAD

**Issue by spyhunter99** [hansmaad/chartist-plugin-zoom#12] opened 2017-05-03 17:42 UTC
I'm getting the above error message, which sources from
`function project(value,axis)`

specifically axis.bounds.max is undefined. I'm not sure what i'm doing wrong. Is it because the x axis on my chart's x axis is a FixedScaleAxis?

**Comment by hansmaad** [comment] 2017-05-04 06:11
Duplicate of #6 
Currently only AutoScaleAxis is supported.

**Comment by spyhunter99** [comment] 2017-05-04 12:59
Ahh thanks. Please consider updating the readme/exampels to reflect this

**Closed as completed** 2017-05-04 14:04 UTC
